export const FETCH_RECEIPT = 'FETCH_RECEIPT';
export const FETCH_RECEIPT_SUCCESS = 'FETCH_RECEIPT_SUCCESS';
export const FETCH_RECEIPT_FAILED = 'FETCH_RECEIPT_FAILED';

export const FETCH_SHIPPING = 'FETCH_SHIPPING';
export const FETCH_SHIPPING_SUCCESS = 'FETCH_SHIPPING_SUCCESS';
export const FETCH_SHIPPING_FAILED = 'FETCH_SHIPPING_FAILED';


export const ADD_RECEIPT = 'ADD_RECEIPT';
export const ADD_RECEIPT_SUCCESS = 'ADD_RECEIPT_SUCCESS';
export const ADD_RECEIPT_FAILED = 'ADD_RECEIPT_FAILED';

export const ADD_SHIPPING = 'ADD_SHIPPING';
export const ADD_SHIPPING_SUCCESS = 'ADD_SHIPPING_SUCCESS';
export const ADD_SHIPPING_FAILED = 'ADD_SHIPPING_FAILED';