export const GET_ALL_ACCOUNTING = 'GET_ALL_ACCOUNTING';

export const GET_ALL_CUSTOMER = 'GET_ALL_CUSTOMER';

export const GET_TOTAL_DEBT_TO_PAY = 'GET_TOTAL_DEBT_TO_PAY';

export const GET_FULFILLMENT = 'GET_FULFILLMENT';

export const CLEAR_FULFILLMENT = 'CLEAR_FULFILLMENT';

export const ADD_ACCOUNTING = 'ADD_ACCOUNTING';

export const UPDATE_ACCOUNTING = 'UPDATE_ACCOUNTING';

export const GET_ONE_ACCOUNTING = 'GET_ONE_ACCOUNTING';

export const GET_HISTORY = 'GET_HISTORY';
