export const GET_ALL_CROSSCHECK = 'GET_ALL_CROSSCHECK';

export const GET_ALL_SHIPPER = 'GET_ALL_SHIPPER';

export const GET_DEBT = 'GET_DEBT';

export const CLEAR = 'CLEAR';

export const GET_FULFILLMENT_OF_SHIPPER = 'GET_FULFILLMENT_OF_SHIPPER';

export const ADD_CROSSCHECK = 'ADD_CROSSCHECK';

export const UPDATE_CROSSCHECK = 'UPDATE_CROSSCHECK';

export const GET_ONE_CROSS = 'GET_ONE_CROSS';

export const GET_FULFILMENT_OF_CROSS = 'GET_FULFILMENT_OF_CROSS';

export const GET_HISTORY = 'GET_HISTORY';
