export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS';
export const FETCH_CUSTOMER_FAILED = 'FETCH_CUSTOMER_FAILED';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_FAILED = 'ADD_CUSTOMER_FAILED';


export const FETCH_CUSTOMER_BY_ID = 'FETCH_CUSTOMER_BY_ID';
export const FETCH_CUSTOMER_BY_ID_SUCCESS = 'FETCH_CUSTOMER_BY_ID_SUCCESS';
export const FETCH_CUSTOMER_BY_ID_FAILED = 'FETCH_CUSTOMER_BY_ID_FAILED';

export const PAGE_NUMBER = 'PAGE_NUMBER';
export const SET_STATUS = 'SET_STATUS';

