export const FETCH_FULFILLMENT = 'FETCH_FULFILLMENT';
export const FETCH_FULFILLMENTS = 'FETCH_FULFILLMENTS';
export const FETCH_FULFILLMENT_SUCCESS = 'FETCH_FULFILLMENT_SUCCESS';
export const FETCH_FULFILLMENT_FAILED = 'FETCH_FULFILLMENT_FAILED';

export const FETCH_FULFILLMENT_BY_ID = 'FETCH_FULFILLMENT_BY_ID';
export const FETCH_FULFILLMENT_BY_ID_SUCCESS = 'FETCH_FULFILLMENT_BY_ID_SUCCESS';
export const FETCH_FULFILLMENT_BY_ID_FAILED = 'FETCH_FULFILLMENT_BY_ID_FAILED';

export const ADD_FULFILLMENT = 'ADD_FULFILLMENT';
export const ADD_FULFILLMENT_SUCCESS = 'ADD_FULFILLMENT_SUCCESS';
export const ADD_FULFILLMENT_FAILED = 'ADD_FULFILLMENT_FAILED';