export const FETCH_PARTNER = 'FETCH_PARTNER';
export const FETCH_PARTNER_SUCCESS = 'FETCH_PARTNER_SUCCESS';
export const FETCH_PARTNER_FAILED = 'FETCH_PARTNER_FAILED';

export const ADD_PARTNER = 'ADD_PARTNER';
export const ADD_PARTNER_SUCCESS = 'ADD_PARTNER_SUCCESS';
export const ADD_PARTNER_FAILED = 'ADD_PARTNER_FAILED';

export const PAGE_NUMBER = 'PAGE_NUMBER';