export const FETCH_SHIPPER = 'FETCH_SHIPPER';
export const FETCH_SHIPPER_SUCCESS = 'FETCH_SHIPPER_SUCCESS';
export const FETCH_SHIPPER_FAILED = 'FETCH_SHIPPER_FAILED';

export const FETCH_SHIPPER_BY_ID = 'FETCH_SHIPPER_BY_ID';
export const FETCH_SHIPPER_BY_ID_SUCCESS = 'FETCH_SHIPPER_BY_ID_SUCCESS';
export const FETCH_SHIPPER_BY_ID_FAILED = 'FETCH_SHIPPER_BY_ID_FAILED';

export const ADD_ITEM_SHIPPER = 'ADD_ITEM_SHIPPER';

export const CLEAR_SHIPPER = 'CLEAR_SHIPPER';